### ISSUE TITLE
Issues with "joepenna"-Term, any other does not work.

### ISSUE THREAD

**Issue by Sor3nt** [JoePenna/Dreambooth-Stable-Diffusion#30]
I tried around a lot and found out that my training data only works when i keep "joepenna" inside https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/main/ldm/data/personalized.py#L11

Lets say i change  "joepenna" inside personalized.py to "mytest"
and call the command with "--class_word mytest" and also (just in case) "-n mytest"

My 3 sample files are named "input/mytest car_01.png", "input/mytest car_02.png", "input/mytest car_02.png"

when i check the training samples, it looks very good.
But when i use then the checkpoint and use the prompt "mytest car" i get a total random image.

If i keep it as "joepenna" in personalized.py then the result works fine with "joepenna car"

is that a bug or i am just stupid ?

**Comment by prsyahmi** [comment]
I never had a problem. I can't think of anything else besides did you save your file?

> But when i use then the checkpoint and use the prompt "mytest car" i get a total random image.

If you use the same checkpoint and use the prompt `joepenna car` did it works? If it is then maybe you just forgot saving, otherwise I don't know.

Change the `personalized.py` to `mytest`
class name: `car`

The prompt should work: eg. `an oil painting of mytest car`

**Comment by ozzeruk** [comment]
I had this issue once. I solved it afterwards by opening personalized.py, changing the tag, then saving it. Then continuing with the script.
