### ISSUE TITLE
Captionizer doesn't seem to do anything?

### ISSUE THREAD

**Issue by aiXander** [JoePenna/Dreambooth-Stable-Diffusion#94]
Could someone explain me what the purpose of the `captionizer` module is?
It is used here in the code, but it simply returns the placeholder_token instead of doing what I thought it would do, which is to generate a plausible caption from the input img...
https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/main/ldm/data/personalized.py#L79

Also, I can't find this package anywhere on GitHub... 
![image](https://user-images.githubusercontent.com/24993604/198647895-cd8e90da-5218-43d8-8707-fb6cd11ac344.png)

**Comment by askibinski** [comment]
@aiXander It's this one https://github.com/fabbarix/captionizer

I stumbled upon this issue when trying to find out how to add metadata/descriptions to training images, which seems like an important step although most tutorials don't even mention it.

Reading that repos readme, it seems the captions are ready by parsing the filename. Maybe a more elegant way would be to have a simple separate description txt file. Not sure how other repos are handling this, since I'm only familiar with this one at this point.

**Comment by askibinski** [comment]
Digging a bit deeper, the token and class are passed here on training:
https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/main/main.py#L662

This works and by default, if you put all your images with whatever filenames in the training_images dir, the caption will become "token class" for all of them. So for example "joepenna person". The filename does not matter.

If you would like to finetune/better caption your images, you can do this like described by the captionizer repo (link in previous comment).

For example you can filename your images like:
```
img-1@S_C_sitting.jpg
img-2@S_C_standing.jpg
img-3@closeup_of_S_C.jpg
```
And then the token and class will be automatically replaced.

However, according to captionizer you can also create multiple subfolders like `/training_images/joepenna/person/` and then those will be used as tokens _instead_ of what is passed as argument from the command. 

This is probably designed by  as a way to be more flexible, but IMO it's unnecessarily complicated and also undocumented thus making it prone to error when users to not understand this and for example change tokens in the command but leave subfolders unchanged.

**Comment by djbielejeski** [comment]
Captioning 101 thread: https://discord.com/channels/1023277529424986162/1029222282511515678
